dist: xenial
language: python
python: 3.7
before_install: pip install --upgrade pip
before_script: pylint 2*
script: ulimit -s 40000; ulimit -a; for d in 2*; do (cd $d; pwd; ls * | xargs -n 1 time python); done;
