on:
  push:
  workflow_dispatch: # Enables on-demand/manual triggering
jobs:
  job:
    strategy:
      fail-fast: false
      matrix:
        version: [3.9, '3.10', 3.11, 3.12, pypy3.9, pypy3.10]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - run: |
          pip install -q -r requirements.txt
          for d in 2*; do (cd $d; pwd; ls * | xargs -n 1 time python); done;
        env:
          SESSION: ${{ secrets.SESSION }}
